### ISSUE TITLE
Are default import/sync services required.

### ISSUE THREAD

**Issue by GrandLTU** [ongr-io/ConnectionsBundle#107]
Here https://github.com/ongr-io/ConnectionsBundle/blob/master/Resources/config/import.yml are defined default services for import and sync.

`ongr_connections.import.modifier` requires some extra configuration for bundle even to work but they have very little use because users will have to define their own services as just one set of services for import very rarely will be enough.
Also they are not tied to any pipeline so they are not usable either.

**Comment by tautrimas** [comment]
@mindaugasbarysas is this ticket correct? Do you have suggestions on the recommended solution?

**Comment by mindaugasbarysas** [comment]
As far as I see, there is no definition for ``ongr.import.modifier.class``. 
It could possibly be a piece of configuration left over from the version when there was a universal modifier class. 
As for the solution: it is possible to have a universal modifier, which sets the document values automatically (see XtCommerceConnectorBundle for a proof-of-concept). And while the end-user would still have to define the pipeline services, as far as I remember, the services defined in ``import.yml`` are meant to be extended upon using ``parent: ongr.import.(.*)``, as this would ensure compatibility between what pipeline expects and end-user defines, so I would suggest:

1) removing ``ongr.import.modifier`` _only_ OR moving functionality from XtCommerceConnectorBundle (which provides universal modifier),
2) leaving the rest of those service definitions intact.

**Comment by tautrimas** [comment]
Actual parameter is defined here: https://github.com/ongr-io/ConnectionsBundle/blob/7196744e952c6889b0950dead81f13ae7fe1b2bf/Tests/app/config/injection_test.yml#L8

Therefore, tests are passing, but in order to use ConnectionsBundle, one has to define that parameter again. Also, parameter definition does not help, because `ongr_connections.import.modifier` is not really useful as it is not tagged. It only creates a problem, because it provides no functionality and forces to define `ongr_connections.import.modifier.class` parameter for no reason.

Solution is to remove this service `ongr_connections.import.modifier` and remove `ongr_connections.import.modifier.class` definitions from connectors that defines it.

**Comment by martiis** [comment]
It has been fixed, by removed parameter from yml files, but the service is left alone as abstract and if there would be a `ongr_connections.import.modifier.class` parameter, compiler would catch that and set it to that abstract service.
