### ISSUE TITLE
Where should be the fixtures located?

### ISSUE THREAD

**Issue by mindaugasbarysas** [ongr-io/ConnectionsBundle#57]
Initiate discussion.

**Comment by tautrimas** [comment]
Suggestions:

1. `Tests/app/fixtures/Foo/{data.xml,DummyLoader.php}`
1. `Tests/Fixtures/Foo/{data.xml,DummyLoader.php}`
1. `Tests/{Unit,Functional}/Fixtures/Foo/{data.xml,DummyLoader.php}`
1. `Tests/Unit/Fixtures/Foo/{data.xml,DummyLoader.php}`
1. `Tests/Functional/Fixtures/Foo/{data.xml,DummyLoader.php}`
1. `Tests/Functional/Foo/Fixture/{data.xml,DummyLoader.php}`

There are advantages and disadvantages in each of them. Since practically there are always Functional tests, fixtures can be placed there under the same path as a Functional test. Unit tests can reuse those fixtures when needed. Therefore, I suggest variant 6.

**Comment by mindaugasbarysas** [comment]
Did we come to an agreement to use variant #3?

**Comment by tautrimas** [comment]
It seems that number 3 is a very natural, flexible and simple choice.
